baseurl = "/"
languageCode = "en-us"
title = "R-SIG Sevilla"
theme = "hugo-lithium"
googleAnalytics = "UA-160645872-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
# Enable comments by entering your Disqus shortname
disqusShortname = "sevillav"

[[menu.main]]
    name = "Inicio"
    url = "https://sevillav.netlify.app/"
[[menu.main]]
    name = "Nosotros"
    url = "https://campoambiente.com/nosotros/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/Campo_Ambiente/"
[[menu.main]]
    name = "CampoAmbiente"
    url = "https://campoambiente.com/"
    
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "ca.ico"

    [params.logo]
    url = "Logo_CA_arroz4.png"
    width = 50
    height = 50
    alt = "Logo"

