---
title: Triangulo textural de suelos
author: Victor Sevilla
date: '2020-03-16'
slug: triangulo1
categories: []
tags: []
---

##Por: CampoAmbiente.com

###palabra clave: **Triangulo textural.**

Mostraremos como realizar un triangulo textural para poder clasificar los valores de porcentajes (%) de arena, Limo y Arcilla de cada horizonte de los suelos. Para esto echaremos mano de la funcion xxxxx del paquete xxxxx, Ver figura 1.

Instalamos el paquete `soiltexture` (si es necesarios) y lo activamos:
```{r}
#install.packages(pkgs = "soiltexture") de esta forma lo instala.

library(soiltexture) #activamos el paquete.
```

```{r}
TT.plot(
class.sys = "USDA-NCSS.TT",
lang = "es2",
main = "Triangulo de Textura de Suelo",
lwd.axis = 1,
cex.lab = 0.7,
cex.axis = 0.7)
```

```{r}
TT.plot(
class.sys = "USDA.TT",
class.p.bg.col = c("aquamarine", "aquamarine2",
"aquamarine3", "cornsilk", "burlywood1",
"burlywood3", "darkseagreen1", "darkseagreen3",
"darkolivegreen1", "darkolivegreen2",
"deepskyblue", "deepskyblue4"),
main = "Triangulo Textural de Suelo segun USDA",
lang = "es2",
lwd.axis = 1,
cex.lab = 0.7,
cex.axis = 0.6)
```

```{r}
TT.classes.tbl (class.sys = "USDA.TT") [ ,1:2]
```

```{r}
data()
```





